"""
Tests for SyntheticFidelityReport.

We use a simple real/synthetic pair where the synthetic is generated by the
InsuranceSynthesizer so we're testing the full pipeline end-to-end, then
checking that the report metrics are structurally correct (right shapes,
right types, valid ranges).

We do not test CatBoost (TSTR) here — it's in optional dependencies and would
make the test suite much slower. There's a separate slow test marker for that.
"""

import numpy as np
import polars as pl
import pytest

from insurance_synthetic import InsuranceSynthesizer, SyntheticFidelityReport


# ---------------------------------------------------------------------------
# Shared fixture: real/synthetic pair
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def real_synthetic_pair(medium_motor_df):
    synth = InsuranceSynthesizer(random_state=42)
    synth.fit(
        medium_motor_df,
        exposure_col="exposure",
        frequency_col="claim_count",
        severity_col="claim_amount",
    )
    synthetic_df = synth.generate(1000)
    return medium_motor_df, synthetic_df


@pytest.fixture(scope="module")
def fidelity_report(real_synthetic_pair):
    real_df, synthetic_df = real_synthetic_pair
    return SyntheticFidelityReport(
        real_df, synthetic_df, exposure_col="exposure", target_col="claim_count"
    )


# ---------------------------------------------------------------------------
# Marginal report
# ---------------------------------------------------------------------------

class TestMarginalReport:
    def test_returns_dataframe(self, fidelity_report):
        result = fidelity_report.marginal_report()
        assert isinstance(result, pl.DataFrame)

    def test_has_expected_columns(self, fidelity_report):
        result = fidelity_report.marginal_report()
        required = {"column", "ks_statistic", "ks_pvalue", "wasserstein",
                    "mean_real", "mean_synthetic", "std_real", "std_synthetic"}
        assert required.issubset(set(result.columns))

    def test_row_count_matches_columns(self, fidelity_report, medium_motor_df):
        result = fidelity_report.marginal_report()
        assert len(result) == len(medium_motor_df.columns)

    def test_ks_statistic_in_zero_one(self, fidelity_report):
        result = fidelity_report.marginal_report()
        numeric_rows = result.filter(pl.col("ks_statistic").is_not_null())
        ks = numeric_rows["ks_statistic"].to_numpy()
        assert (ks >= 0).all()
        assert (ks <= 1).all()

    def test_wasserstein_non_negative(self, fidelity_report):
        result = fidelity_report.marginal_report()
        numeric_rows = result.filter(pl.col("wasserstein").is_not_null())
        wass = numeric_rows["wasserstein"].to_numpy()
        assert (wass >= 0).all()

    def test_good_synthesis_ks_below_threshold(self, fidelity_report):
        """
        For a well-fitted synthesiser on 1000 rows with 1000 synthetic,
        most columns should have KS stat < 0.15 (a loose threshold for small n).
        """
        result = fidelity_report.marginal_report()
        numeric_rows = result.filter(pl.col("ks_statistic").is_not_null())
        median_ks = float(numeric_rows["ks_statistic"].median())
        assert median_ks < 0.2, f"Median KS {median_ks:.3f} is too high"


# ---------------------------------------------------------------------------
# Correlation report
# ---------------------------------------------------------------------------

class TestCorrelationReport:
    def test_returns_dataframe(self, fidelity_report):
        result = fidelity_report.correlation_report()
        assert isinstance(result, pl.DataFrame)

    def test_has_expected_columns(self, fidelity_report):
        result = fidelity_report.correlation_report()
        required = {"col_a", "col_b", "spearman_real", "spearman_synthetic",
                    "delta", "frobenius_norm"}
        assert required.issubset(set(result.columns))

    def test_correlations_in_minus_one_to_one(self, fidelity_report):
        result = fidelity_report.correlation_report()
        r = result["spearman_real"].to_numpy()
        s = result["spearman_synthetic"].to_numpy()
        assert (r >= -1.0).all() and (r <= 1.0).all()
        assert (s >= -1.0).all() and (s <= 1.0).all()

    def test_delta_non_negative(self, fidelity_report):
        result = fidelity_report.correlation_report()
        assert (result["delta"].to_numpy() >= 0).all()

    def test_sorted_by_delta_descending(self, fidelity_report):
        result = fidelity_report.correlation_report()
        deltas = result["delta"].to_numpy()
        assert all(deltas[i] >= deltas[i + 1] for i in range(len(deltas) - 1))

    def test_frobenius_norm_positive(self, fidelity_report):
        result = fidelity_report.correlation_report()
        frob = float(result["frobenius_norm"][0])
        assert frob >= 0.0


# ---------------------------------------------------------------------------
# TVaR ratio
# ---------------------------------------------------------------------------

class TestTVaRRatio:
    def test_returns_float(self, fidelity_report):
        ratio = fidelity_report.tvar_ratio("claim_count")
        assert isinstance(ratio, float)

    def test_tvar_ratio_positive(self, fidelity_report):
        ratio = fidelity_report.tvar_ratio("claim_count")
        assert ratio >= 0.0

    def test_tvar_ratio_at_different_percentiles(self, fidelity_report):
        """TVaR ratio should be computable at various percentiles."""
        for p in [0.90, 0.95, 0.99]:
            r = fidelity_report.tvar_ratio("claim_count", percentile=p)
            assert np.isfinite(r)

    def test_tvar_ratio_of_identical_data(self):
        """TVaR ratio of identical data should be 1.0."""
        rng = np.random.default_rng(42)
        data = rng.lognormal(5, 1.2, size=500)
        df = pl.DataFrame({"x": data.tolist(), "exposure": [1.0] * 500})
        report = SyntheticFidelityReport(df, df, target_col="x")
        ratio = report.tvar_ratio("x")
        assert ratio == pytest.approx(1.0, abs=1e-6)


# ---------------------------------------------------------------------------
# Exposure-weighted KS
# ---------------------------------------------------------------------------

class TestExposureWeightedKS:
    def test_returns_float(self, fidelity_report):
        result = fidelity_report.exposure_weighted_ks("driver_age")
        assert isinstance(result, float)

    def test_in_zero_one(self, fidelity_report):
        result = fidelity_report.exposure_weighted_ks("driver_age")
        assert 0.0 <= result <= 1.0

    def test_missing_exposure_warns(self, real_synthetic_pair):
        real_df, synthetic_df = real_synthetic_pair
        report = SyntheticFidelityReport(
            real_df.drop("exposure"),
            synthetic_df.drop("exposure"),
            exposure_col="exposure",
            target_col="claim_count",
        )
        with pytest.warns(UserWarning, match="Exposure"):
            result = report.exposure_weighted_ks("driver_age")
        assert isinstance(result, float)


# ---------------------------------------------------------------------------
# to_markdown
# ---------------------------------------------------------------------------

class TestMarkdownReport:
    def test_returns_string(self, fidelity_report):
        md = fidelity_report.to_markdown()
        assert isinstance(md, str)
        assert len(md) > 100

    def test_contains_section_headers(self, fidelity_report):
        md = fidelity_report.to_markdown()
        assert "Marginal Fidelity" in md
        assert "Correlation Fidelity" in md
        assert "Tail Risk" in md

    def test_contains_column_names(self, fidelity_report, medium_motor_df):
        md = fidelity_report.to_markdown()
        for col in ["driver_age", "exposure", "claim_count"]:
            assert col in md

    def test_markdown_table_formatting(self, fidelity_report):
        md = fidelity_report.to_markdown()
        # Should contain pipe-delimited table rows
        lines = [l for l in md.split("\n") if "|" in l]
        assert len(lines) > 5


# ---------------------------------------------------------------------------
# Missing columns warning
# ---------------------------------------------------------------------------

class TestMissingColumnWarning:
    def test_warns_on_missing_synthetic_columns(self, medium_motor_df):
        reduced = medium_motor_df.drop("claim_amount")
        with pytest.warns(UserWarning, match="missing columns"):
            report = SyntheticFidelityReport(medium_motor_df, reduced, target_col="claim_count")
        # marginal report should still work for shared columns
        marg = report.marginal_report()
        assert isinstance(marg, pl.DataFrame)
