"""
Synthetic data fidelity assessment for insurance portfolios.

Generating synthetic data is only half the job. The other half is proving it's
good enough to use — that the synthetic portfolio behaves like the real one
from a pricing model's perspective.

We measure fidelity at three levels:
1. Marginal fidelity: does each synthetic column match the real distribution?
2. Correlation fidelity: does the dependence structure match?
3. Predictive fidelity (TSTR): if you train a model on synthetic and test on
   real, does it score as well as training on real data?

The TSTR (Train-on-Synthetic, Test-on-Real) score is the most demanding test.
It's the standard in the synthetic data literature (Jordon et al., 2022) and
the most meaningful for actuarial use cases — a synthetic portfolio is fit for
purpose if and only if models trained on it generalise to real data.

CatBoost is used for TSTR because it handles mixed types natively and matches
what UK pricing teams actually use for GLM alternatives. It's in optional
dependencies so the rest of the library works without it.
"""

from __future__ import annotations

import warnings
from typing import Optional

import numpy as np
import polars as pl
from scipy import stats


class SyntheticFidelityReport:
    """
    Quantitative fidelity assessment comparing real and synthetic portfolios.

    Parameters
    ----------
    real_df : pl.DataFrame
        The original (real) portfolio data used to fit the synthesiser.
    synthetic_df : pl.DataFrame
        The synthetic portfolio generated by InsuranceSynthesizer.generate().
    exposure_col : str
        Name of the exposure column. Used for exposure-weighted metrics.
    target_col : str
        Name of the primary modelling target (typically claim_count).
        Used for TVaR and TSTR metrics.
    """

    def __init__(
        self,
        real_df: pl.DataFrame,
        synthetic_df: pl.DataFrame,
        exposure_col: str = "exposure",
        target_col: str = "claim_count",
    ):
        self.real_df = real_df
        self.synthetic_df = synthetic_df
        self.exposure_col = exposure_col
        self.target_col = target_col

        # Validate columns match
        missing = set(real_df.columns) - set(synthetic_df.columns)
        if missing:
            warnings.warn(
                f"Synthetic DataFrame is missing columns: {missing}. "
                "Some metrics will be unavailable.",
                UserWarning,
                stacklevel=2,
            )

    def marginal_report(self) -> pl.DataFrame:
        """
        Per-column marginal fidelity statistics.

        Returns a DataFrame with columns:
        - column: column name
        - ks_statistic: Kolmogorov-Smirnov test statistic
        - ks_pvalue: KS test p-value (< 0.05 = distributions differ significantly)
        - wasserstein: Wasserstein-1 distance (normalised by real std)
        - mean_real: mean of the real column
        - mean_synthetic: mean of the synthetic column
        - std_real: std of the real column
        - std_synthetic: std of the synthetic column
        """
        rows = []
        common_cols = [c for c in self.real_df.columns if c in self.synthetic_df.columns]

        for col in common_cols:
            real_col = self.real_df[col]
            synth_col = self.synthetic_df[col]

            # Skip non-numeric columns for KS/Wasserstein
            if real_col.dtype in (pl.Utf8, pl.Categorical, pl.String):
                rows.append({
                    "column": col,
                    "ks_statistic": None,
                    "ks_pvalue": None,
                    "wasserstein": None,
                    "mean_real": None,
                    "mean_synthetic": None,
                    "std_real": None,
                    "std_synthetic": None,
                })
                continue

            r = real_col.drop_nulls().to_numpy().astype(float)
            s = synth_col.drop_nulls().to_numpy().astype(float)

            if len(r) == 0 or len(s) == 0:
                rows.append({
                    "column": col,
                    "ks_statistic": None,
                    "ks_pvalue": None,
                    "wasserstein": None,
                    "mean_real": None,
                    "mean_synthetic": None,
                    "std_real": None,
                    "std_synthetic": None,
                })
                continue

            ks_stat, ks_pval = stats.ks_2samp(r, s)

            # Wasserstein distance, normalised by real std (scale-invariant)
            real_std = float(np.std(r))
            wass = float(stats.wasserstein_distance(r, s))
            wass_norm = wass / real_std if real_std > 0 else wass

            rows.append({
                "column": col,
                "ks_statistic": float(ks_stat),
                "ks_pvalue": float(ks_pval),
                "wasserstein": float(wass_norm),
                "mean_real": float(np.mean(r)),
                "mean_synthetic": float(np.mean(s)),
                "std_real": float(np.std(r)),
                "std_synthetic": float(np.std(s)),
            })

        return pl.DataFrame(rows)

    def correlation_report(self) -> pl.DataFrame:
        """
        Spearman rank correlation comparison.

        Returns a DataFrame with columns:
        - col_a, col_b: the pair of columns
        - spearman_real: Spearman correlation in the real data
        - spearman_synthetic: Spearman correlation in the synthetic data
        - delta: absolute difference
        - frobenius_norm: Frobenius norm of the correlation matrix difference,
          normalised by the number of columns d so it is comparable across
          different-width datasets.
        """
        numeric_cols = [
            c for c in self.real_df.columns
            if c in self.synthetic_df.columns
            and self.real_df[c].dtype not in (pl.Utf8, pl.Categorical, pl.String)
        ]

        n_cols = len(numeric_cols)
        real_mat = np.zeros((n_cols, n_cols))
        synth_mat = np.zeros((n_cols, n_cols))

        real_arrays = {c: self.real_df[c].to_numpy().astype(float) for c in numeric_cols}
        synth_arrays = {c: self.synthetic_df[c].to_numpy().astype(float) for c in numeric_cols}

        rows = []
        for i, ca in enumerate(numeric_cols):
            for j, cb in enumerate(numeric_cols):
                if i > j:
                    continue
                r_corr, _ = stats.spearmanr(real_arrays[ca], real_arrays[cb])
                s_corr, _ = stats.spearmanr(synth_arrays[ca], synth_arrays[cb])
                real_mat[i, j] = real_mat[j, i] = float(r_corr)
                synth_mat[i, j] = synth_mat[j, i] = float(s_corr)
                if i < j:
                    rows.append({
                        "col_a": ca,
                        "col_b": cb,
                        "spearman_real": float(r_corr),
                        "spearman_synthetic": float(s_corr),
                        "delta": float(abs(r_corr - s_corr)),
                    })

        # Frobenius norm normalised by d so it's comparable across datasets
        # with different numbers of columns.
        d = max(n_cols, 1)
        frobenius = float(np.linalg.norm(real_mat - synth_mat, "fro")) / d
        result = pl.DataFrame(rows).sort("delta", descending=True)

        # Attach the Frobenius norm as metadata via a column constant
        result = result.with_columns(
            pl.lit(frobenius).alias("frobenius_norm")
        )
        return result

    def tvar_ratio(self, col: str, percentile: float = 0.99) -> float:
        """
        Ratio of synthetic TVaR to real TVaR at the given percentile.

        A value close to 1.0 indicates the synthetic data preserves the tail
        behaviour of the real portfolio. Values > 1 mean the synthetic data
        is heavier-tailed than the real; < 1 means lighter-tailed.

        Parameters
        ----------
        col : str
            Column to compute TVaR for (typically 'claim_amount').
        percentile : float
            VaR percentile to condition on (default 0.99 = 99th percentile).

        Returns
        -------
        float
            synthetic_TVaR / real_TVaR
        """
        r = self.real_df[col].drop_nulls().to_numpy().astype(float)
        s = self.synthetic_df[col].drop_nulls().to_numpy().astype(float)

        real_tvar = _tvar(r, percentile)
        synth_tvar = _tvar(s, percentile)

        if real_tvar == 0:
            raise ValueError(f"Real TVaR at {percentile:.0%} is zero — cannot compute ratio.")

        return float(synth_tvar / real_tvar)

    def exposure_weighted_ks(self, col: str) -> float:
        """
        Exposure-weighted KS statistic for a given column.

        Standard KS treats each policy equally. But pricing teams care more
        about errors in large-exposure segments (full-year policies) than in
        mid-term cancellations. This weighted variant resamples from both
        distributions proportional to exposure before running KS.

        Parameters
        ----------
        col : str
            Column to test.

        Returns
        -------
        float
            KS statistic from the exposure-weighted comparison.
        """
        if self.exposure_col not in self.real_df.columns:
            warnings.warn(
                f"Exposure column '{self.exposure_col}' not found. "
                "Returning unweighted KS.",
                UserWarning,
                stacklevel=2,
            )
            r = self.real_df[col].to_numpy().astype(float)
            s = self.synthetic_df[col].to_numpy().astype(float)
            ks, _ = stats.ks_2samp(r, s)
            return float(ks)

        real_exposure = self.real_df[self.exposure_col].to_numpy().astype(float)
        synth_exposure = self.synthetic_df[self.exposure_col].to_numpy().astype(float)
        real_vals = self.real_df[col].to_numpy().astype(float)
        synth_vals = self.synthetic_df[col].to_numpy().astype(float)

        # Draw samples proportional to exposure
        rng = np.random.default_rng(0)
        n = len(real_vals)
        real_probs = real_exposure / real_exposure.sum()
        synth_probs = synth_exposure / synth_exposure.sum()

        real_sample = rng.choice(real_vals, size=n, replace=True, p=real_probs)
        synth_sample = rng.choice(synth_vals, size=n, replace=True, p=synth_probs)

        ks, _ = stats.ks_2samp(real_sample, synth_sample)
        return float(ks)

    def tstr_score(
        self,
        test_fraction: float = 0.2,
        catboost_iterations: int = 200,
        random_state: int = 42,
    ) -> float:
        """
        Train-on-Synthetic, Test-on-Real (TSTR) Gini gap.

        Fits a CatBoost regressor on synthetic data, a second on a real
        training set (same 80/20 split), then evaluates both on the real
        holdout. The Gini gap is real_gini - synthetic_gini. Values near 0
        mean the synthetic model is as predictive as the real one.

        Both models are trained on the same fraction of rows (1 - test_fraction)
        so the comparison is fair. The real model uses the real training split;
        the synthetic model uses all of synthetic_df (same size by convention
        or truncated to match).

        The loss function is chosen automatically based on the target column
        dtype: integer columns use Poisson loss (appropriate for claim counts),
        float/continuous columns use RMSE (appropriate for severities and
        premiums).

        Requires catboost to be installed (`pip install insurance-synthetic[fidelity]`).

        Parameters
        ----------
        test_fraction : float
            Fraction of the real data held out for evaluation. The real model
            trains on (1 - test_fraction) of the real data. The synthetic model
            trains on the same number of synthetic rows.
        catboost_iterations : int
            Number of CatBoost boosting rounds. Keep low for a quick check.
        random_state : int

        Returns
        -------
        float
            Gini gap = real_gini - synthetic_gini. Closer to 0 is better.
        """
        try:
            from catboost import CatBoostRegressor, Pool  # type: ignore
        except ImportError:
            raise ImportError(
                "CatBoost is required for TSTR score. "
                "Install with: pip install insurance-synthetic[fidelity]"
            )

        if self.target_col not in self.real_df.columns:
            raise ValueError(f"Target column '{self.target_col}' not in real_df.")

        feature_cols = [
            c for c in self.real_df.columns
            if c != self.target_col
        ]
        cat_features = [
            c for c in feature_cols
            if self.real_df[c].dtype in (pl.Utf8, pl.Categorical, pl.String)
        ]

        # Detect whether the target is count/integer (use Poisson loss) or
        # continuous/float (use RMSE). Poisson loss is appropriate for claim
        # counts; RMSE is safer for severity and premium columns that can have
        # arbitrary non-negative float values.
        target_dtype = self.real_df[self.target_col].dtype
        _integer_dtypes = (
            pl.Int8, pl.Int16, pl.Int32, pl.Int64,
            pl.UInt8, pl.UInt16, pl.UInt32, pl.UInt64,
        )
        loss_function = "Poisson" if target_dtype in _integer_dtypes else "RMSE"

        # Split real data into train / test
        rng = np.random.default_rng(random_state)
        n_real = len(self.real_df)
        test_idx = rng.choice(n_real, size=int(n_real * test_fraction), replace=False)
        train_idx = np.setdiff1d(np.arange(n_real), test_idx)

        real_train = self.real_df[train_idx.tolist()]
        real_test = self.real_df[test_idx.tolist()]

        # Use the same number of training rows for both models so the
        # comparison is apples-to-apples. Truncate synthetic if it is larger.
        n_train = len(real_train)
        synth_train = self.synthetic_df[:n_train]

        x_real_train = real_train.select(feature_cols).to_pandas()
        y_real_train = real_train[self.target_col].to_numpy()
        x_synth_train = synth_train.select(feature_cols).to_pandas()
        y_synth_train = synth_train[self.target_col].to_numpy()
        x_test = real_test.select(feature_cols).to_pandas()
        y_test = real_test[self.target_col].to_numpy()

        # Encode cat features as strings for CatBoost
        for col in cat_features:
            x_real_train[col] = x_real_train[col].astype(str)
            x_synth_train[col] = x_synth_train[col].astype(str)
            x_test[col] = x_test[col].astype(str)

        cat_idx = [x_real_train.columns.get_loc(c) for c in cat_features]

        common_params = {
            "iterations": catboost_iterations,
            "learning_rate": 0.1,
            "depth": 4,
            "loss_function": loss_function,
            "verbose": False,
            "random_seed": random_state,
        }

        # Train on real
        model_real = CatBoostRegressor(**common_params)
        model_real.fit(x_real_train, y_real_train, cat_features=cat_idx)

        # Train on synthetic
        model_synth = CatBoostRegressor(**common_params)
        model_synth.fit(x_synth_train, y_synth_train, cat_features=cat_idx)

        # Evaluate both on real test set
        pred_real = model_real.predict(x_test)
        pred_synth = model_synth.predict(x_test)

        real_gini = _gini(y_test, pred_real)
        synth_gini = _gini(y_test, pred_synth)

        return float(real_gini - synth_gini)

    def to_markdown(self) -> str:
        """
        Full fidelity report as a markdown string.

        Suitable for pasting into a Confluence page, notebook, or README.
        """
        lines = [
            "# Synthetic Data Fidelity Report",
            "",
            "## Overview",
            f"- Real data: {len(self.real_df):,} rows, {len(self.real_df.columns)} columns",
            f"- Synthetic data: {len(self.synthetic_df):,} rows, {len(self.synthetic_df.columns)} columns",
            f"- Target column: `{self.target_col}`",
            f"- Exposure column: `{self.exposure_col}`",
            "",
            "## Marginal Fidelity",
            "",
            "KS statistic < 0.05 is excellent. Wasserstein (normalised) < 0.1 is good.",
            "",
        ]

        try:
            marg = self.marginal_report()
            lines.append("| Column | KS stat | KS p-value | Wasserstein (norm) | Mean (real) | Mean (synth) |")
            lines.append("|--------|---------|------------|-------------------|-------------|--------------|")
            for row in marg.iter_rows(named=True):
                ks = f"{row['ks_statistic']:.4f}" if row["ks_statistic"] is not None else "—"
                ksp = f"{row['ks_pvalue']:.4f}" if row["ks_pvalue"] is not None else "—"
                wass = f"{row['wasserstein']:.4f}" if row["wasserstein"] is not None else "—"
                mr = f"{row['mean_real']:.3f}" if row["mean_real"] is not None else "—"
                ms = f"{row['mean_synthetic']:.3f}" if row["mean_synthetic"] is not None else "—"
                lines.append(f"| {row['column']} | {ks} | {ksp} | {wass} | {mr} | {ms} |")
        except Exception as exc:
            lines.append(f"*Marginal report failed: {exc}*")

        lines += ["", "## Correlation Fidelity", ""]
        try:
            corr = self.correlation_report()
            frob = float(corr["frobenius_norm"][0])
            lines.append(f"Frobenius norm distance (normalised by d): **{frob:.4f}**")
            lines.append("")
            lines.append("Top pairs by absolute correlation difference:")
            lines.append("")
            lines.append("| Col A | Col B | Spearman (real) | Spearman (synth) | Delta |")
            lines.append("|-------|-------|-----------------|------------------|-------|")
            for row in corr.head(10).iter_rows(named=True):
                lines.append(
                    f"| {row['col_a']} | {row['col_b']} | "
                    f"{row['spearman_real']:.3f} | {row['spearman_synthetic']:.3f} | "
                    f"{row['delta']:.3f} |"
                )
        except Exception as exc:
            lines.append(f"*Correlation report failed: {exc}*")

        lines += ["", "## Tail Risk (TVaR Ratio)", ""]
        try:
            if self.target_col in self.real_df.columns:
                ratio = self.tvar_ratio(self.target_col)
                lines.append(
                    f"TVaR ratio at 99th percentile for `{self.target_col}`: **{ratio:.4f}** "
                    f"(target ≈ 1.0)"
                )
            else:
                lines.append(f"*Target column `{self.target_col}` not found.*")
        except Exception as exc:
            lines.append(f"*TVaR ratio failed: {exc}*")

        lines += ["", "---", "_Report generated by insurance-synthetic_"]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Statistical helpers
# ---------------------------------------------------------------------------

def _tvar(values: np.ndarray, percentile: float) -> float:
    """
    Tail Value at Risk (CVaR) at the given percentile.

    Standard actuarial definition: E[X | X > q_p] using strict inequality.
    This ensures we are averaging only the values strictly beyond the VaR
    threshold, not including the threshold itself.
    """
    threshold = np.quantile(values, percentile)
    tail = values[values > threshold]
    if len(tail) == 0:
        return float(threshold)
    return float(np.mean(tail))


def _gini(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    """
    Normalised Gini coefficient (2 * AUC - 1) for regression.

    The standard insurance pricing discrimination metric. The formula
    computes twice the area between the model Lorenz curve and the diagonal:

        Gini = 2 * sum(cumsum_y) / (n * sum_y) - (n+1)/n

    which is approximately 2*AUC - 1 for large n. The factor of 2 is required
    to scale the concentration statistic into the standard [-1, 1] range.

    Higher is better (more discriminating model).
    """
    n = len(y_true)
    if n == 0:
        return 0.0
    order = np.argsort(y_pred)[::-1]
    y_sorted = y_true[order]
    cumsum = np.cumsum(y_sorted)
    gini = (np.sum(cumsum) / np.sum(y_true) - (n + 1) / 2) / n
    return float(gini * 2)
